### ISSUE TITLE
q1: 選択肢Aが解答であるはずだが、動かない。

### ISSUE THREAD

**Issue by meri25** [meri25/MS-70-483-Training#2]
1. タイトルについて、下記エラーが発生しています。
`System.InvalidCastException: 'Unable to cast object of type 'Enumerator' to type 'System.Collections.Generic.List`1[System.String]'.'`

@shibatea

**Comment by shibatea** [comment]
- [IEnumerable.GetEnumerator メソッド](https://docs.microsoft.com/ja-jp/dotnet/api/system.collections.ienumerable.getenumerator?view=netframework-4.8)
- [System.InvalidCastException クラス](https://docs.microsoft.com/ja-jp/dotnet/api/system.invalidcastexception?view=netframework-4.8)

![image](https://user-images.githubusercontent.com/31196732/76135096-4abcb300-6067-11ea-9af2-fb965bfc5093.png)

今回は無効なキャスト（オブジェクトの型変換）が発生して InvalidCastExcaption が発生しています。

IEnumerable.GetEnumerator メソッドの戻り値は `IEnumerator` です。
それに対して `List<string>` にキャストしようとしてます。

**列挙子** と呼ばれるクラスを作るための `IEnumerator` インタフェースについて理解することをオススメします。

ちなみに、エラーを発生させたくないならキャストさせなければいいだけです。

- 参考
  - [foreach - C# によるプログラミング入門 | ++C++; // 未確認飛行 C](https://ufcpp.net/study/csharp/sp_foreach.html)

@meri25

**Comment by shibatea** [comment]
Q1に対するサンプルコードを追記したプルリクエストを発行しました。
https://github.com/meri25/MS-70-483-Training/pull/3

**Comment by meri25** [comment]
行き詰ってめげていました。回答 & サンプルコード、ありがとうございます！
この issue は close します。
