### ISSUE TITLE
q6: 正解と不正解の根拠がわからない

### ISSUE THREAD

**Issue by meri25** [meri25/MS-70-483-Training#4]
Question.6 についてです。
問題文と正解は READMR.md を参照していただきたいです。

疑問
Option.3
`Create` メソッドを利用して `Connection_3` を作成したいのであれば、Option.3 の `Create` メソッドを呼び出せば、対象のインスタンスは作成できます。しかし、こちらは不正解とのこと。どうして不正解なのでしょうか。

Option.4
- どうして正解なのでしょうか。
- どうして `protected Connection_4()...` が必要なのでしょうか。

@shibatea

**Comment by shibatea** [comment]
設問の内容から Connection クラスの必要条件は以下の２つ
1. Createメソッドを呼び出して、Connectionの新しいインスタンスを他のクラスでのみ作成できるようにする必要があります。
2. ソリューションでは、クラスがConnectionから継承できるようにする必要があります。

2つ目の条件は Connection クラスが継承可能なクラスであることをいっています。
つまり、親クラスとして正しい記述は Option.3 と Option.4 の内、どちらなのかを考えればよいわけです。

継承の仕様の１つとして、親クラスと子クラスのコンストラクターの呼び出し順序と実行順序にルールがあります。

例えば、あるモジュールから子クラスが new されたとしてます。（＝子クラスのコンストラクターが呼ばれることと同義）
その時の親クラス、子クラスの呼び出し順序と実行順序は以下の通りです。

1. 子クラスのコンストラクターが呼ばれる
2. 親クラスのコンストラクターが呼ばれる
3. 親クラスのコンストラクターが実行される
4. 子クラスのコンストラクターが実行される

ということで、子クラスが new されると親クラスのコンストラクターが呼び出されて、実行されます。

Option.3 は、親クラスのコンストラクターが private なため、子クラスから親クラスのコンストラクターが呼べません。そもそもコンパイルエラーになります。

```
public class ChildConnection : Connection_3
{
    // これはコンパイルエラーになります
}
```

Option.4 は、親クラスのコンストラクターが protected なため、子クラスからアクセス可能になります。そのため、コンパイルエラーにならずに子クラスから親クラスのコンストラクターが呼べます。

```
public class ChildConnection : Connection_4
{
    // これはコンパイルエラーになりません
}
```

以上より、Option.4 が正解。

@meri25

**Comment by shibatea** [comment]
> 疑問
Option.3
Create メソッドを利用して Connection_3 を作成したいのであれば、Option.3 の Create メソッドを呼び出せば、対象のインスタンスは作成できます。しかし、こちらは不正解とのこと。どうして不正解なのでしょうか。

上のコメントにも書いた通り、親クラスとして不適切な記述なので不正解です。

> Option.4
どうして正解なのでしょうか。
どうして protected Connection_4()... が必要なのでしょうか。

１つ目の要件として Create メソッドを経由して Connection クラスのインスタンスを生成したいとあります。Connection クラスのコンストラクターの修飾子を `public` にすると、Create メソッドじゃなくても new することで Connection クラスのインスタンスが生成できちゃいます。

その為、外部から new されたくない、でも子クラスからは参照できるようにしたい、という要件を満たすために `protected` にする必要があります。

@meri25

**Comment by meri25** [comment]
`protected` の利用方法について理解しました。
回答ありがとうございます！
この Issue はクローズいたします。
@shibatea
