### ISSUE TITLE
コーディング規約について

### ISSUE THREAD

**Issue by meri25** [meri25/MS-70-483-Training#5]
命名規則について質問です。

C# Doocs に次のようなサンプルがありました。
サンプルでは、メソッドの先頭文字が小文字ですが、なぜでしょうか。
メソッドの先頭は大文字始まりがコーディング規約にありますが、メソッド名の先頭が小文字になるパターンもあるのでしょうか。
ある場合、どういった場合にメソッドの先頭文字が小文字になるか教えていただきたいです。

```c#
public class SampleDelegate
    {
        // int を取り込んで String を返すメソッドのデリゲートを宣言する
        public delegate String myMethodDeleate(int myInt);
        // デリゲートがポイントできるメソッドを定義する
        public class mySampleClass
        {
            // インスタンスメソッドを定義する
            public String myStringMethod(int myInt)  { ... }
        }
        // static メソッドを定義する
        public static String mySignMethod(int myInt)  { ... }
        public static void SampleDelegateMain()  { ... }
    }
```

もとのサンプルサードは[こちら](https://docs.microsoft.com/ja-jp/dotnet/api/system.delegate?view=netframework-4.8)です。
@shibatea

**Comment by shibatea** [comment]
戻り値の型が先頭大文字の String という表記からして、Java っぽく書かれてるようですね。
MS 公式的に先頭小文字の string を使うことが推奨されてるようなので、このサンプルコードについてはコーディング規約云々は無視して良いと思います。

@meri25

**Comment by meri25** [comment]
コメントありがとうございます。
では、コーディング規約に従うならば、戻り値も「string」 にすべきでしょうか？
@shibatea

**Comment by shibatea** [comment]
C# においてプリミティブ型は全部小文字表記のエイリアスを使いましょう。string とか int とか unit とか。
@meri25

**Comment by meri25** [comment]
かしこです！
ありがとうございます。
この Issue は Close します。
