### ISSUE TITLE
Question.1-8 で解答の根拠がわからない。

### ISSUE THREAD

**Issue by meri25** [meri25/MS-70-483-Training#6]
[ 質問 ]
1. Question.1-8 でなぜ D が解答となるのかがわかりません。
2. 「式の構文が1回だけ評価される」条件を満たすものが分かりません。

[README/Question.1-8](https://github.com/meri25/MS-70-483-Training#question1-8)

> Regexクラスを使用して一部の文字列入力データを検証する必要があるC＃アプリケーションを開発しています。
https://www.gratisexam.com/
アプリケーションには、ContainsHyperlinkという名前のメソッドが含まれています。
ContainsHyperlink（）メソッドは、URIと周囲のマークアップの存在を検証します。
次のコードセグメントは、ContainsHyperlink（）メソッドを定義しています。
（行番号は参照用にのみ含まれています。）
各検証関数に使用される式パターンは一定です。
Regexオブジェクトが最初にインスタンス化されるときに、式の構文が1回だけ評価されるようにする必要があります。
行04にどのコードセグメントを挿入する必要がありますか？

```c#
        bool ConstainsHyperLink(string inputData)
        {
            string regExPattern = "href\\s*=\\s*(?:\"(?<1>[^\"]*)\"|(?<1>\\S+))";

            // Option.A
            var evaluator = new Regex(regExPattern, RegexOptions.CultureInvariant);

            // Option.B
            // var evaluator = new Regex(inputData);

            // Option.C
            /*
                var assemblyName = "Vlidation";
                var compilationInfo = new RegexCompilationInfo(inputData, RegexOptions.IgnoreCase, "Href", assemblyName, true);
                Regex.CompileToAssembly(new[] { compilationInfo }, new AssemblyName(assemblyName));
                var evaluator = new Regex(regExPattern, RegexOptions.CultureInvariant); 
            */

            // Option.D
            // var evaluator = new Regex(regExPattern, RegexOptions.Compiled);

            return evaluator.IsMatch(inputData);

        }
```
@shibatea

**Comment by shibatea** [comment]
ConstainsHyperLink メソッドは、入力データを検証する度に呼ばれるメソッドです。

Option.A や Option.B のように Regex クラスを Complied オプションなしで毎回インスタンス化するのは極めて非効率な実装です。

![image](https://user-images.githubusercontent.com/31196732/77246217-4fd55100-6c68-11ea-98f6-9f5ea1a0e208.png)
参考：[.NET の正規表現に関するベスト プラクティス](https://docs.microsoft.com/ja-jp/dotnet/standard/base-types/best-practices?view=netframework-4.8#static-regular-expressions)

Regex クラスをインスタンス化する際に Complied オプションを指定すると、正規表現パターン（今回の例だと `href\\s*=\\s*(?:\"(?<1>[^\"]*)\"|(?<1>\\S+))`）を良い感じにキャッシュしてくれるみたいです。そして、一度キャッシュされた正規表現パターンはそれを再利用してくれるので、効率的とのことです。

![image](https://user-images.githubusercontent.com/31196732/77246286-1e10ba00-6c69-11ea-8481-e81609254f66.png)

参考：[解釈される正規表現とコンパイルされる正規表現](https://docs.microsoft.com/ja-jp/dotnet/standard/base-types/best-practices?view=netframework-4.8#interpreted-vs-compiled-regular-expressions)

問題文にある `式の構文が1回だけ評価されるようにする必要があります` というのは、Complied オプションを指定して非効率な実装を避けることと、Complied オプションを使うことで正規表現パターンを1回評価することでキャッシュされる、という仕組みの理解を問う問題なんだと思います。

今回の Issue を頂いたことで C# の正規表現について理解が深まったので感謝してます！

@meri25
